name: Update README

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 */1 * * *"

jobs:
  markscribe:
    runs-on: ubuntu-latest

    steps:
      - name: "deneme"
        env:
          GITHUB_TOKEN: ${{ vars.PERSONAL_GITHUB_TOKEN}}
        run:
         echo " [${{vars.PERSONAL_GITHUB_TOKEN}}"
      - uses: actions/checkout@master

      - uses: muesli/readme-scribe@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          template: "README.template.md"
          writeTo: "README.md"  

      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GIHUB_TOKEN }}
        with:
          commit_message: Update generated README
          branch: master
          commit_user_name: ramazantufekci
          commit_user_email: actions@github.com
          commit_author: ramazantufekci
