name: Update README

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 */1 * * *"

jobs:
  markscribe:
    runs-on: ubuntu-latest
    steps:
      - name: "deneme"
        env:
          GITHUB_TOKEN: ${{ vars.PERSONAL_GITHUB_TOKEN}}
        run:
         echo " [${{vars.PERSONAL_GITHUB_TOKEN}}"
      - uses: actions/checkout@master

      - uses: muesli/readme-scribe@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          template: "README.template.md"
          writeTo: "README.md"  
      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GIHUB_TOKEN }}
        with:
          commit_message: Update generated README
          branch: master
          
  update-readme:
    runs-on: ubuntu-latest
    needs: markscribe
    steps:
      - name: Repo klonla
        uses: actions/checkout@v4

      - name: Python kurulum
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: README dosyasını oluştur
        run: python .github/scripts/update_readmee.py

      - name: Commit ve push et
        run: |
          git pull
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "README otomatik güncellendi" || echo "Değişiklik yok"
          git push
  
          
