name: simple
on:
  push:
  
jobs:
  build:
    runs-on:
      - self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: "selam"
        uses: actions-hub/kubectl@master
        with:
          args: apply -f kubernetes/deployment.yml
        
