name: Template to Readme

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 */12 * * *"  # Her 12 saatte bir çalışır
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install readme-scribe
        run: |
          go install github.com/muesli/readme-scribe@latest

      - name: Generate README
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          readme-scribe generate
          
      - name: Update README Stats URLs
        run: |
          d=$(date '+%s')
          sed -i "s/api?username=ramazantufekci/api?username=ramazantufekci\&cache_seconds=1800\&timestamp=$d/g" README.md
          
      - name: Commit and Push
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions[Bot]"
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "docs: Update README"
          git push
